"""empty message

Revision ID: 37f00103bef8
Revises: 4a3a05da42d9
Create Date: 2020-03-08 21:05:41.613678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f00103bef8'
down_revision = '4a3a05da42d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user_roles', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_roles', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
