"""empty message

Revision ID: b2bf2b8196b5
Revises: fc94f7452b61
Create Date: 2020-03-09 20:28:20.944256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bf2b8196b5'
down_revision = 'fc94f7452b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'department', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'user_id')
    # ### end Alembic commands ###
