"""empty message

Revision ID: e96a765a3a7c
Revises: 3cd512448308
Create Date: 2020-03-09 20:43:09.615401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96a765a3a7c'
down_revision = '3cd512448308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'department', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'user_id')
    # ### end Alembic commands ###
