"""empty message

Revision ID: fc94f7452b61
Revises: 5707eeed0789
Create Date: 2020-03-09 15:56:47.054463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc94f7452b61'
down_revision = '5707eeed0789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('title', sa.String(length=50), nullable=True))
    op.drop_constraint('department_name_key', 'department', type_='unique')
    op.create_unique_constraint(None, 'department', ['title'])
    op.drop_column('department', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'department', type_='unique')
    op.create_unique_constraint('department_name_key', 'department', ['name'])
    op.drop_column('department', 'title')
    # ### end Alembic commands ###
